---
- hosts: all
  sudo: true
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: Setting hostname
      hostname: name="edx-analytics-devstack"
  roles:
    - { role: analytics_dev }
